[dependencies]
base = "0.10.4"
array = "https://github.com/aviate-labs/array.mo#v0.2.0"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
xtended-numbers = "0.1.1"
itertools = "0.1.1"
icrc1 = "https://github.com/NatLabs/icrc1#master@0800c7ac03026a4c5a72eeb357cbbd0aca2f0fb4"

[package]
name = "icrc1"
version = "0.1.0"
description = "icrc1"
repository = "https://github.com/NatLabs/icrc1"